# **NUMPY**

NumPy bir Python kütüphanesidir.

NumPy, dizilerle çalışmak için kullanılır.

NumPy, "Numerical Python" kelimelerinin kısaltmasıdır.

NumPy nedir?

NumPy, dizilerle çalışmak için kullanılan bir Python kütüphanesidir.

Ayrıca doğrusal cebir, Fourier dönüşümü ve matrisler alanında çalışma işlevlerine de sahiptir.

NumPy, 2005 yılında Travis Oliphant tarafından oluşturulmuştur. Açık kaynaklı bir projedir ve özgürce kullanabilirsiniz.

NumPy, Numerical Python'ın kısaltmasıdır.

NumPy'ı Neden Kullanmalıyız?

Python'da dizilerin işlevini gören listelerimiz var, ancak bunların işlenmesi yavaş oluyor.

NumPy, geleneksel Python listelerine göre 50 kata kadar daha hızlı bir dizi nesnesi sağlamayı hedefliyor.

NumPy'deki dizi nesnesine `array` denir ndarrayve onunla çalışmayı çok kolaylaştıran birçok yardımcı fonksiyon sağlar ndarray.

Hız ve kaynakların çok önemli olduğu veri biliminde diziler çok sık kullanılır.

Veri Bilimi: Verilerin nasıl depolandığını, kullanıldığını ve analiz edildiğini, böylece bunlardan bilgi elde edildiğini inceleyen bilgisayar biliminin bir dalıdır.

NumPy neden listelerden daha hızlı?

NumPy dizileri, listelerin aksine bellekte tek bir sürekli yerde saklanır, bu nedenle işlemler bunlara çok verimli bir şekilde erişebilir ve bunları işleyebilir.

Bu davranışa bilgisayar biliminde referans yerelliği denir.

Bu, NumPy'nin listelerden daha hızlı olmasının ana nedenidir. Ayrıca, en yeni CPU mimarileriyle çalışacak şekilde optimize edilmiştir.



In [ ]:
#Şu komutu kullanarak yükleyin:
#pip install numpy

In [ ]:
#NumPy yüklendikten sonra, uygulamalarınıza importşu anahtar kelimeyi ekleyerek içe aktarın:

import numpy

**NumPy, np olarak**

NumPy genellikle takma ad altında içe aktarılır np .

Takma ad: Python'da takma adlar, aynı şeye atıfta bulunmak için kullanılan alternatif isimlerdir.

asİçe aktarma sırasında anahtar kelimeyle bir takma ad oluşturun :

**import numpy as np**

npArtık NumPy paketine yerine şeklinde atıfta bulunulabilir numpy.

In [2]:
#Bir NumPy dizisi oluşturun:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#numpy versiyon kontrolü için

import numpy as np

print(np.__version__)

In [3]:

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
#List ve tuple veri versek te çıktı aynı olur
arr = np.array((1, 2, 3, 4, 5))

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
#Değeri 42 olan 0 boyutlu bir dizi oluşturun.

import numpy as np

arr = np.array(42)

print(arr)

42


In [10]:
#1, 2, 3, 4, 5 değerlerini içeren tek boyutlu bir dizi oluşturun:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [11]:
#1, 2, 3 ve 4, 5, 6 değerlerini içeren iki diziden oluşan 2 boyutlu bir dizi oluşturun:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
#İki adet 2 boyutlu diziden oluşan bir 3 boyutlu dizi oluşturun; her iki 2 boyutlu dizi de içinde 1, 2, 3 ve 4, 5, 6 değerlerini içeren iki dizi içermelidir:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [13]:
#Dizilerin kaç boyuta sahip olduğunu kontrol edin:

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
#Beş boyutlu bir dizi oluşturun ve gerçekten beş boyuta sahip olduğunu doğrulayın:

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [15]:
#Aşağıdaki diziden ilk elemanı alın:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [16]:
#Aşağıdaki diziden üçüncü ve dördüncü elemanları alın ve bunları toplayın.
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [17]:
#İki boyutlu dizilerdeki elemanlara erişmek için, boyutu ve elemanın indeksini temsil eden virgülle ayrılmış tamsayılar kullanabiliriz.

#İki boyutlu dizileri, boyutun satırı, indeksin ise sütunu temsil ettiği, satır ve sütunlardan oluşan bir tablo gibi düşünün.

#Birinci satırın ikinci sütunundaki öğeye erişin:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
#İkinci satır, beşinci sütundaki öğeye erişin:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

In [18]:
#Üç boyutlu dizilerdeki elemanlara erişmek için, boyutları ve elemanın indeksini temsil eden virgülle ayrılmış tamsayılar kullanabiliriz.
#Birinci dizinin ikinci dizisinin üçüncü öğesine erişin:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [19]:
#2. boyuttaki son elemanı yazdırın:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# **Dilimleme**

Python'da dilimleme, belirli bir indeksten başka bir belirli indekse elemanları taşımak anlamına gelir.

İndeks yerine dilim (slice) iletiyoruz, şu şekilde: .[start:end]

Adımı şu şekilde de tanımlayabiliriz: .[start:end:step]

Başlangıç ​​noktasını geçemezsek, puan 0 olarak kabul edilir.

Eğer "end" belirtmezsek, bu, o boyuttaki dizinin uzunluğu olarak kabul edilir.

Bu adımı geçemezsek 1. adım olarak kabul edilir.

In [20]:
#Aşağıdaki diziden 1. indeksten 5. indekse kadar olan elemanları dilimleyin:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [21]:
#Dizinin 4. indeksinden sonuna kadar olan elemanları dilimle:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [ ]:
#Öğeleri baştan 4. indekse kadar dilimleyin (dahil değildir):

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

In [22]:
#Sondan 3. indeksten sondan 1. indekse kadar olan kesit:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [25]:
#1. indeksten 5. indekse kadar her iki elemandan birini döndürün:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [24]:
#Dizinin tamamından her iki elemandan birini döndürün:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [26]:
#İkinci öğeden başlayarak, 1. indeksten 4. indekse kadar olan öğeleri dilimleyin (dahil değildir):

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [29]:
#Her iki öğeden de 2. indeksi döndürün:

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [30]:
#Her iki öğeden de, 1. indeksten 4. indekse kadar (dahil değil) dilimleme işlemi, 2 boyutlu bir dizi döndürecektir:

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# **NumPy'de Veri Tipleri**

In [31]:
#Bir dizi nesnesinin veri türünü alın:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [32]:
#Dizeler içeren bir dizinin veri türünü alın:

import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


Belirli bir veri türüyle diziler oluşturma

Diziler oluşturmak için bu fonksiyonu kullanıyoruz array(); bu fonksiyon isteğe bağlı bir argüman alabilir: dtype bu argüman, dizi elemanlarının beklenen veri türünü tanımlamamıza olanak tanır:

In [35]:
#Veri türü string olan bir dizi oluşturun:

import numpy as np

arr = np.array([1, 2, 3, 4],dtype='S')

print(arr)
print(arr.dtype)

[1 2 3 4]
int64


Bir değer dönüştürülemezse ne olur?

Eğer elemanları dönüştürülemeyen bir tür verilirse, NumPy bir ValueError hatası verecektir.

In [37]:
import numpy as np

#arr = np.array(['a', '2', '3'], dtype='i')

**Mevcut Dizilerde Veri Türü Dönüştürme**

Mevcut bir dizinin veri türünü değiştirmenin en iyi yolu, ilgili yöntemle dizinin bir kopyasını oluşturmaktır astype().

Bu astype()fonksiyon, dizinin bir kopyasını oluşturur ve veri türünü parametre olarak belirtmenize olanak tanır.

'f'Veri türü, float, integer vb. gibi bir dize kullanılarak belirtilebilir veya float ve integer 'i'gibi doğrudan veri türü kullanılabilir .floatint

In [38]:
#'i'Parametre değeri olarak şunu kullanarak veri türünü float'tan tamsayıya değiştirin :

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [39]:
#intParametre değeri olarak şunu kullanarak veri türünü float'tan tamsayıya değiştirin :

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [40]:
#Veri türünü tamsayıdan boolean'a değiştirin:

import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [41]:
#Bir kopyasını oluşturun, orijinal diziyi değiştirin ve her iki diziyi de görüntüleyin:
#Kopya ile yeni bir nesne oluşur.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [42]:
#Bir görünüm oluşturun, orijinal diziyi değiştirin ve her iki diziyi de görüntüleyin:
# Görüntüleme yoluyla oluşturulan nesnedeki değişiklik orjinal de de değişikliğe neden olur.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [44]:
#Bir görünüm oluşturun, görünümü değiştirin ve her iki diziyi de görüntüleyin:
#Orijinal dizi, görünümde yapılan değişikliklerden etkilenmelidir.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [45]:
#Bir dizinin verilerine sahip olup olmadığını kontrol etmek için temel özniteliğin değerini yazdırın:
#Kopyalama işlemi sonucu döndürür None.
#Görünüm ise orijinal diziyi döndürür.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [46]:
#İki boyutlu bir dizinin şeklini yazdırın:
# örnek (2, 4), dizinin 2 boyuta sahip olduğunu, birinci boyutta 2, ikinci boyutta ise 4 eleman bulunduğunu gösteren bir değer döndürür.
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [48]:
#1, 2, 3, 4 değerlerini içeren bir vektör kullanarak 5 boyutlu bir dizi oluşturun ndminve son boyutun değerinin 4 olduğunu doğrulayın:
# 4. indekste 4 değeri var, dolayısıyla 5. (4 + 1.) boyutun 4 elemanı olduğunu söyleyebiliriz.

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [49]:
#Aşağıdaki 12 elemanlı 1 boyutlu diziyi 2 boyutlu diziye dönüştürün.

#En dıştaki boyutta, her biri 3 elemandan oluşan 4 dizi bulunacaktır:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [50]:
#Aşağıdaki 12 elemanlı 1 boyutlu diziyi 3 boyutlu diziye dönüştürün.

#En dıştaki boyutta, her biri 2 eleman içeren 3 diziden oluşan 2 dizi bulunacaktır:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [51]:
#Döndürülen dizinin bir kopya mı yoksa bir görünüm mü olduğunu kontrol edin:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [52]:
#Diziyi 1 boyutlu bir diziye dönüştürün:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [53]:
#Aşağıdaki tek boyutlu dizinin elemanları üzerinde yineleme yapın:

import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [54]:
#Aşağıdaki 2 boyutlu dizinin elemanları üzerinde yineleme yapın:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [55]:
#İki boyutlu dizinin her bir skalar elemanı üzerinde yineleme yapın:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [56]:
#Aşağıdaki 3 boyutlu dizinin elemanları üzerinde yineleme yapın:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [57]:
#Skaler değerlere kadar yineleme yapın:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [58]:
#Aşağıdaki 3 boyutlu diziyi yineleyerek inceleyin:

import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [60]:
#Diziyi bir dize olarak yineleyin:

import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [61]:
#Aşağıdaki 1 boyutlu dizilerin elemanlarını numaralandırın:

import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [62]:
#Aşağıdaki 2 boyutlu dizinin elemanlarını numaralandırın:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [63]:
#İki diziyi birleştirin

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [64]:
#İki boyutlu iki diziyi satırlar boyunca (eksen=1) birleştirin:

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [65]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [66]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [67]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [68]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [69]:
#Diziyi 3 parçaya bölün:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [70]:
#Diziyi 4 parçaya bölün:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [72]:
#Bölünmüş dizilere erişin:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [73]:
#İki boyutlu diziyi üç adet iki boyutlu diziye bölün.

import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [74]:
#İki boyutlu diziyi üç adet iki boyutlu diziye bölün.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
#İki boyutlu diziyi sütunlar boyunca üç adet iki boyutlu diziye bölün.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

In [ ]:
#Bu yöntemi kullanarak hsplit()2 boyutlu diziyi sütunlar boyunca üç adet 2 boyutlu diziye bölün.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

In [75]:
#Değeri 4 olan indeksleri bulun:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [76]:
#Değerlerin çift olduğu indeksleri bulun:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [77]:
#Değerlerin tek olduğu indeksleri bulun:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


In [78]:
#7 değerinin eklenmesi gereken indeksleri bulun:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [80]:
#Sağdan başlayarak, 7 değerinin eklenmesi gereken indeksleri bulun:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [81]:
#2, 4 ve 6 değerlerinin ekleneceği indeksleri bulun:

import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [ ]:
#Diziyi sıralayın:

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

In [ ]:
#Diziyi alfabetik olarak sıralayın:

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

In [ ]:
#Mantıksal (boolean) bir diziyi sırala:

import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

In [82]:
#İki boyutlu bir diziyi sıralayın:

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [83]:
#0 ve 2. indekslerdeki elemanlardan bir dizi oluşturun:

import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [84]:
#Yalnızca 42'den yüksek değerleri döndürecek bir filtre dizisi oluşturun:

import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [85]:
#Orijinal diziden yalnızca çift elemanları döndürecek bir filtre dizisi oluşturun:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [86]:
#Yalnızca 42'den yüksek değerleri döndürecek bir filtre dizisi oluşturun:

import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [87]:
#Orijinal diziden yalnızca çift elemanları döndürecek bir filtre dizisi oluşturun:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
